### ISSUE TITLE
Copy after build and generated files

### ISSUE THREAD

**Issue by romanlex** [marverix/rollup-plugin-copier#1]
Can I copy builded library file with this plugin?
My output section is
```
output: {
    file: `build/libs/mylib/latest/mylib.js`,
    format: 'umd',
    name: 'MyUMDLibrary',
  },
```

I want copy builded target from `build/libs/mylib/latest/mylib.js` to `build/libs/mylib/v0.1.2/mylib.js`

**Comment by marverix** [comment]
Hello,
sorry for so long response time - I didn't get email notification from GH about your issue.
Yes, it's possible. This should work:
```
  copier({
    items: [
      {
        src: 'build/libs/mylib/latest/mylib.js',
        dest: 'build/libs/mylib/v0.1.2/mylib.js',
        createPath: true
      }
    ],
    hookOn: 'writeBundle'
  })
```
